$fa = 0.1;
$fs = 0.1;


KEYCAP_HEIGHT=0.7;
KEYCAP_UPPER_THICKNESS=0.2;
KEYCAP_INNER_HEIGHT=KEYCAP_HEIGHT-KEYCAP_UPPER_THICKNESS;
KEYCAP_DIAM=6.0;
KEYCAP_INNER_DIAM=3.25;

difference(){
    cylinder(h=KEYCAP_HEIGHT,r=KEYCAP_DIAM/2, center=true);
    translate([0,0,(-(KEYCAP_HEIGHT-KEYCAP_INNER_HEIGHT)/2)-0.001])
    cylinder(h=KEYCAP_INNER_HEIGHT, r=KEYCAP_INNER_DIAM/2, center=true);
}